#!/usr/bin/env python3
"""Build skill graph — maps skills to their MCP tool and file dependencies.

Scans .claude/skills/*/{CLAUDE,SKILL}.md and extracts:
  - Tools mentioned (mcp__*, Bash, Edit, etc.)
  - Scripts invoked (scripts/*.py, scripts/*.sh)
  - Other skills referenced (/skill-name patterns)

Writes .ai/skill-graph.md — a Markdown table + adjacency list for quick
reference by Claude when choosing tools or debugging skill failures.

Exits 0 always. Run at session Stop or manually: python3 scripts/build-skill-graph.py
"""
import os
import re
import sys
from pathlib import Path

# Paths can be overridden via env vars for portability across repos/templates
_default_root = Path(__file__).resolve().parent.parent
# As a plugin Stop hook (run after `cd $CLAUDE_PROJECT_DIR`), graph the consumer
# project; AI_REPO_ROOT still wins for explicit overrides.
REPO_ROOT   = Path(os.environ.get("AI_REPO_ROOT") or os.environ.get("CLAUDE_PROJECT_DIR") or str(_default_root))
SKILLS_DIR  = Path(os.environ.get("AI_SKILLS_DIR",  str(REPO_ROOT / ".claude" / "skills")))
OUTPUT_FILE = Path(os.environ.get("AI_SKILL_GRAPH", str(REPO_ROOT / ".ai" / "skill-graph.md")))

# Patterns to extract from skill files
RE_MCP_TOOL    = re.compile(r'\b(mcp__[\w]+__[\w]+)\b')
RE_NATIVE_TOOL = re.compile(r'\b(Bash|Edit|Write|Read|Glob|Grep|Agent|WebFetch|WebSearch|TodoWrite|ToolSearch)\b')
RE_SCRIPT      = re.compile(r'scripts/[\w\-\.]+\.(?:py|sh)')  # non-capturing group → returns full path
RE_SKILL_REF   = re.compile(r'(?<![\w:/])/([a-z][a-z0-9\-]+)')  # /skill-name refs (skip URL/path segments)


def parse_skill(path: Path) -> dict:
    text = path.read_text(errors="replace")
    return {
        "name": path.parent.name,
        "mcp_tools":    sorted(set(RE_MCP_TOOL.findall(text))),
        "native_tools": sorted(set(RE_NATIVE_TOOL.findall(text))),
        "scripts":      sorted(set(RE_SCRIPT.findall(text))),
        "skill_refs":   sorted(set(RE_SKILL_REF.findall(text))),
    }


def main() -> None:
    if not SKILLS_DIR.exists():
        print(f"No skills directory at {SKILLS_DIR} — skipping skill graph build.")
        sys.exit(0)

    skill_files = sorted(
        p for p in SKILLS_DIR.glob("*/*.md")
        if p.name in ("CLAUDE.md", "SKILL.md")
    )
    if not skill_files:
        print("No skill files found — skipping skill graph build.")
        sys.exit(0)

    skills = [parse_skill(f) for f in skill_files]

    lines = [
        "# Skill Graph",
        "",
        "_Auto-generated by `scripts/build-skill-graph.py`. Do not edit manually._",
        "",
        "## Summary Table",
        "",
        "| Skill | MCP Tools | Native Tools | Scripts | Skill Refs |",
        "|-------|-----------|--------------|---------|------------|",
    ]

    for s in skills:
        mcp    = "<br>".join(s["mcp_tools"])    or "—"
        native = "<br>".join(s["native_tools"]) or "—"
        scripts= "<br>".join(s["scripts"])      or "—"
        refs   = "<br>".join(f"/{r}" for r in s["skill_refs"] if r != s["name"]) or "—"
        lines.append(f"| `{s['name']}` | {mcp} | {native} | {scripts} | {refs} |")

    lines += [
        "",
        "## Adjacency List",
        "",
        "_Skills that reference other skills (skill dependency graph):_",
        "",
    ]

    skill_names = {s["name"] for s in skills}
    for s in skills:
        deps = [r for r in s["skill_refs"] if r in skill_names and r != s["name"]]
        if deps:
            lines.append(f"- **{s['name']}** → {', '.join(f'`{d}`' for d in deps)}")

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text("\n".join(lines) + "\n")
    print(f"Skill graph written to {OUTPUT_FILE} ({len(skills)} skills)")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"build-skill-graph: error (non-fatal): {e}")
    sys.exit(0)
